keep_columns:
    - Income
    - Recency
    - NumWebVisitsMonth
    - Complain
    - age
    - total_purchases
    - enrollment_years
    - family_size

remove_outliers_threshold:
  age: 80
  income: 500000